[build-system]
requires = ["setuptools>= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37

[testenv]
deps = pytest
    pytest-cov
commands = pytest --cov=multiuserpad
"""
